### ISSUE TITLE
Can't run the server

### ISSUE THREAD

**Issue by halimahexe** [fac29/P1DAAF#45]
When running `npm run dev`, we got this issue:

```
> p1daaf@1.0.0 dev
> nodemon src/index.ts

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
```

I assume this may be to do with not having nodemon installed globally on my machine, but this isn't covered in the README, so clarity is needed.

**Comment by halimahexe** [comment]
We had to delete the eslint and nodemon packages in `package.json` to install all of the necessary packages.

**Comment by AlexVOiceover** [comment]
Removed ESlint and added nodemon to dependencies
