### ISSUE TITLE
how to do the search bar

### ISSUE THREAD

**Issue by diddydeeable** [fac29/P1DAAF#85]
Backend Querying

Advantages:

Scalability: Suitable for large datasets.
Security: Data is kept secure on the server, preventing exposure of sensitive information.
Complex Queries: Easier to handle complex queries and join operations.
Performance: Backend databases are optimized for querying large datasets efficiently.

Disadvantages:

Network Latency: Each search query requires a network request, which can introduce latency.
Increased Server Load: The server has to handle all search queries, which can increase its load.

Frontend Querying

Advantages:

Speed: For small datasets, querying on the frontend can provide instantaneous results since it eliminates the network request.
Reduced Server Load: No need to hit the server for each query, reducing server load.
Better User Experience: Provides instant feedback to the user.

Disadvantages:

Data Size Limitation: Not suitable for large datasets as it would consume too much memory and slow down the browser.
Security: Sensitive data exposed in the frontend can be a security risk.
Limited Query Capabilities: More complex queries are harder to implement and slower in JavaScript.

Recommendation
Given that you are using a Node.js backend and a React frontend, it is generally recommended to perform the search query on the backend, especially if:

Your dataset is large.
You have security concerns about exposing data.
Your queries are complex.

**Comment by AlexPD93** [comment]
I vote for backend querying!

**Comment by diddydeeable** [comment]
sounds good, ok I am happy to go with backend.
